services:
  db:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../vrdb_partial_dump.sql:/docker-entrypoint-initdb.d/01_vrdb.sql:ro
    ports:
      - "3306:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
