// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzakemberKereso.Models;

#nullable disable

namespace SzakemberKereso.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260316182731_RenamedExpertOccupaitonPlusMinorStuff")]
    partial class RenamedExpertOccupaitonPlusMinorStuff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("_user_tokens", (string)null);
                });

            modelBuilder.Entity("SzakemberKereso.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publishing_date");

                    b.Property<float?>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("rating");

                    b.Property<string>("TextContent")
                        .HasColumnType("longtext")
                        .HasColumnName("text_content");

                    b.HasKey("Id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Expert", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Biography")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("biography");

                    b.HasKey("UserId");

                    b.ToTable("experts");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ExpertSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpertId")
                        .HasColumnType("int")
                        .HasColumnName("expert_id");

                    b.Property<int>("OccupationId")
                        .HasColumnType("int")
                        .HasColumnName("occupation_id");

                    b.HasKey("Id");

                    b.HasIndex("OccupationId");

                    b.HasIndex("ExpertId", "OccupationId")
                        .IsUnique();

                    b.ToTable("expert_specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertId = 4,
                            OccupationId = 7521
                        },
                        new
                        {
                            Id = 2,
                            ExpertId = 5,
                            OccupationId = 7524
                        },
                        new
                        {
                            Id = 3,
                            ExpertId = 5,
                            OccupationId = 7223
                        },
                        new
                        {
                            Id = 4,
                            ExpertId = 6,
                            OccupationId = 7223
                        },
                        new
                        {
                            Id = 5,
                            ExpertId = 7,
                            OccupationId = 7535
                        });
                });

            modelBuilder.Entity("SzakemberKereso.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DetailId")
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    b.Property<int?>("ExpertId")
                        .HasColumnType("int")
                        .HasColumnName("expert_id");

                    b.Property<int>("InitiatingUserId")
                        .HasColumnType("int")
                        .HasColumnName("initiating_user_id");

                    b.Property<int>("LaborFee")
                        .HasColumnType("int")
                        .HasColumnName("labor_fee");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("InitiatingUserId");

                    b.HasIndex("LocationId");

                    b.HasIndex("StateId");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("SzakemberKereso.Models.JobState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_state_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("job_states");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feor_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("occupations");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ResidentialAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("residential_address_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingName")
                        .HasColumnType("longtext")
                        .HasColumnName("building_name");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("int")
                        .HasColumnName("building_number");

                    b.Property<int?>("DoorNumber")
                        .HasColumnType("int")
                        .HasColumnName("door_number");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int")
                        .HasColumnName("floor_number");

                    b.Property<int>("SettlementId")
                        .HasColumnType("int")
                        .HasColumnName("settlement_id");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("street_name");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.ToTable("residential_addresses");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SzakemberKereso.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_in_minutes");

                    b.Property<int>("ExpertSpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("expert_specialties_id");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("max_price");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ExpertSpecialtyId");

                    b.ToTable("services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            DurationInMinutes = 0,
                            ExpertSpecialtyId = 1,
                            MaxPrice = 0m,
                            MinPrice = 0m,
                            Name = "Sarokszelep cserélés"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            DurationInMinutes = 0,
                            ExpertSpecialtyId = 2,
                            MaxPrice = 0m,
                            MinPrice = 0m,
                            Name = "Mennyezeit lámpa beépítés"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            DurationInMinutes = 0,
                            ExpertSpecialtyId = 3,
                            MaxPrice = 0m,
                            MinPrice = 0m,
                            Name = "Szekrény javítás"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            DurationInMinutes = 0,
                            ExpertSpecialtyId = 4,
                            MaxPrice = 0m,
                            MinPrice = 0m,
                            Name = "Szoba kifestése"
                        });
                });

            modelBuilder.Entity("SzakemberKereso.Models.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("settlement_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("county_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int")
                        .HasColumnName("postal_code");

                    b.HasKey("Id");

                    b.ToTable("settlements");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Studies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("ExpertSpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("expert_specialties_id");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("institution_name");

                    b.Property<int?>("OccupationId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("ExpertSpecialtyId");

                    b.HasIndex("OccupationId");

                    b.ToTable("studies");
                });

            modelBuilder.Entity("SzakemberKereso.Models.TimeInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("time_interval_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("time_intervals");
                });

            modelBuilder.Entity("SzakemberKereso.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SzakemberKereso.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SzakemberKereso.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakemberKereso.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SzakemberKereso.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SzakemberKereso.Models.Expert", b =>
                {
                    b.HasOne("SzakemberKereso.Models.User", "User")
                        .WithOne("Expert")
                        .HasForeignKey("SzakemberKereso.Models.Expert", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ExpertSpecialty", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Expert", "Expert")
                        .WithMany("ExpertSpecialties")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakemberKereso.Models.Occupation", "Occupation")
                        .WithMany("ExpertSpecialties")
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Occupation");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Job", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Expert", "Expert")
                        .WithMany("Jobs")
                        .HasForeignKey("ExpertId");

                    b.HasOne("SzakemberKereso.Models.User", "InitiatingUser")
                        .WithMany("InitiatedJobs")
                        .HasForeignKey("InitiatingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakemberKereso.Models.ResidentialAddress", "Location")
                        .WithMany("Jobs")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakemberKereso.Models.JobState", "State")
                        .WithMany("Jobs")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("InitiatingUser");

                    b.Navigation("Location");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ResidentialAddress", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Settlement", "Settlement")
                        .WithMany("Addresses")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Service", b =>
                {
                    b.HasOne("SzakemberKereso.Models.ExpertSpecialty", "ExpertSpecialty")
                        .WithMany("Services")
                        .HasForeignKey("ExpertSpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpertSpecialty");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Studies", b =>
                {
                    b.HasOne("SzakemberKereso.Models.ExpertSpecialty", "ExpertSpecialty")
                        .WithMany()
                        .HasForeignKey("ExpertSpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakemberKereso.Models.Occupation", null)
                        .WithMany("Studies")
                        .HasForeignKey("OccupationId");

                    b.Navigation("ExpertSpecialty");
                });

            modelBuilder.Entity("SzakemberKereso.Models.TimeInterval", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Job", "Job")
                        .WithMany("TimeIntervals")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Expert", b =>
                {
                    b.Navigation("ExpertSpecialties");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ExpertSpecialty", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Job", b =>
                {
                    b.Navigation("TimeIntervals");
                });

            modelBuilder.Entity("SzakemberKereso.Models.JobState", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Occupation", b =>
                {
                    b.Navigation("ExpertSpecialties");

                    b.Navigation("Studies");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ResidentialAddress", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Settlement", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("SzakemberKereso.Models.User", b =>
                {
                    b.Navigation("Expert");

                    b.Navigation("InitiatedJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
