// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzakemberKereso.Models;

#nullable disable

namespace SzakemberKereso.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260404190239_RemoveDurationAddJobDescription")]
    partial class RemoveDurationAddJobDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("_user_tokens", (string)null);
                });

            modelBuilder.Entity("SzakemberKereso.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publishing_date");

                    b.Property<float?>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("rating");

                    b.Property<string>("TextContent")
                        .HasColumnType("longtext")
                        .HasColumnName("text_content");

                    b.HasKey("Id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Expert", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Biography")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("biography");

                    b.HasKey("UserId");

                    b.ToTable("experts");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ExpertSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpertId")
                        .HasColumnType("int")
                        .HasColumnName("expert_id");

                    b.Property<int>("OccupationId")
                        .HasColumnType("int")
                        .HasColumnName("occupation_id");

                    b.HasKey("Id");

                    b.HasIndex("OccupationId");

                    b.HasIndex("ExpertId", "OccupationId")
                        .IsUnique();

                    b.ToTable("expert_specialties");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("InitiatingUserId")
                        .HasColumnType("int")
                        .HasColumnName("initiating_user_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<int?>("PricingId")
                        .HasColumnType("int")
                        .HasColumnName("pricing_id");

                    b.Property<float?>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("rating");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("InitiatingUserId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PricingId");

                    b.HasIndex("ServiceId");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feor_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("occupations");

                    b.HasData(
                        new
                        {
                            Id = 7223,
                            Description = "",
                            Name = "Bútorasztalos"
                        },
                        new
                        {
                            Id = 7511,
                            Description = "",
                            Name = "Kőműves"
                        },
                        new
                        {
                            Id = 7513,
                            Description = "",
                            Name = "Ács"
                        },
                        new
                        {
                            Id = 7521,
                            Description = "",
                            Name = "Vezeték- és csőhálózat-szerelő (víz, gáz, fűtés)"
                        },
                        new
                        {
                            Id = 7524,
                            Description = "",
                            Name = "Épületvillamossági szerelő, villanyszerelő"
                        },
                        new
                        {
                            Id = 7532,
                            Description = "",
                            Name = "Tetőfedő"
                        },
                        new
                        {
                            Id = 7534,
                            Description = "",
                            Name = "Burkoló"
                        },
                        new
                        {
                            Id = 7535,
                            Description = "",
                            Name = "Festő és mázoló"
                        });
                });

            modelBuilder.Entity("SzakemberKereso.Models.Pricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pricing_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FixedPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fixed_price");

                    b.Property<int>("PricingType")
                        .HasColumnType("int")
                        .HasColumnName("pricing_type");

                    b.Property<string>("UnitName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("unit_name");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.ToTable("pricing");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ResidentialAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("residential_address_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingName")
                        .HasColumnType("longtext")
                        .HasColumnName("building_name");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("int")
                        .HasColumnName("building_number");

                    b.Property<int?>("DoorNumber")
                        .HasColumnType("int")
                        .HasColumnName("door_number");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int")
                        .HasColumnName("floor_number");

                    b.Property<int>("SettlementId")
                        .HasColumnType("int")
                        .HasColumnName("settlement_id");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("street_name");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.ToTable("residential_addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingNumber = 12,
                            SettlementId = 1,
                            StreetName = "Fő utca"
                        },
                        new
                        {
                            Id = 2,
                            BuildingNumber = 3,
                            SettlementId = 1,
                            StreetName = "Petőfi utca"
                        },
                        new
                        {
                            Id = 3,
                            BuildingNumber = 7,
                            SettlementId = 2,
                            StreetName = "Kossuth tér"
                        },
                        new
                        {
                            Id = 4,
                            BuildingNumber = 21,
                            SettlementId = 3,
                            StreetName = "Dózsa György út"
                        },
                        new
                        {
                            Id = 5,
                            BuildingNumber = 5,
                            SettlementId = 4,
                            StreetName = "Rákóczi Ferenc utca"
                        },
                        new
                        {
                            Id = 6,
                            BuildingNumber = 14,
                            SettlementId = 5,
                            StreetName = "Szabadság tér"
                        },
                        new
                        {
                            Id = 7,
                            BuildingNumber = 12,
                            SettlementId = 9,
                            StreetName = "Zrínyi Ilona u."
                        });
                });

            modelBuilder.Entity("SzakemberKereso.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SzakemberKereso.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("ExpertSpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("expert_specialties_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("PricingId")
                        .HasColumnType("int")
                        .HasColumnName("pricing_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpertSpecialtyId");

                    b.HasIndex("PricingId");

                    b.ToTable("services");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("settlement_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("county_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int")
                        .HasColumnName("postal_code");

                    b.HasKey("Id");

                    b.ToTable("settlements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountyName = "Fejér",
                            Name = "Aba",
                            PostalCode = 8127
                        },
                        new
                        {
                            Id = 2,
                            CountyName = "Jász-Nagykun-Szolnok",
                            Name = "Abádszalók",
                            PostalCode = 5241
                        },
                        new
                        {
                            Id = 3,
                            CountyName = "Baranya",
                            Name = "Abaliget",
                            PostalCode = 7678
                        },
                        new
                        {
                            Id = 4,
                            CountyName = "Heves",
                            Name = "Abasár",
                            PostalCode = 3261
                        },
                        new
                        {
                            Id = 5,
                            CountyName = "Borsod-Abaúj-Zemplén",
                            Name = "Abaújalpár",
                            PostalCode = 3882
                        },
                        new
                        {
                            Id = 6,
                            CountyName = "Borsod-Abaúj-Zemplén",
                            Name = "Abaújkér",
                            PostalCode = 3882
                        },
                        new
                        {
                            Id = 7,
                            CountyName = "Borsod-Abaúj-Zemplén",
                            Name = "Abaújlak",
                            PostalCode = 3815
                        },
                        new
                        {
                            Id = 8,
                            CountyName = "Borsod-Abaúj-Zemplén",
                            Name = "Abaújszántó",
                            PostalCode = 3881
                        },
                        new
                        {
                            Id = 9,
                            CountyName = "Vas",
                            Name = "Szombathely",
                            PostalCode = 9700
                        });
                });

            modelBuilder.Entity("SzakemberKereso.Models.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("study_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("ExpertSpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("expert_specialties_id");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("institution_name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("ExpertSpecialtyId");

                    b.ToTable("studies");
                });

            modelBuilder.Entity("SzakemberKereso.Models.TimeInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("time_interval_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("time_intervals");
                });

            modelBuilder.Entity("SzakemberKereso.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SzakemberKereso.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SzakemberKereso.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakemberKereso.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SzakemberKereso.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SzakemberKereso.Models.Expert", b =>
                {
                    b.HasOne("SzakemberKereso.Models.User", "User")
                        .WithOne("Expert")
                        .HasForeignKey("SzakemberKereso.Models.Expert", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ExpertSpecialty", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Expert", "Expert")
                        .WithMany("ExpertSpecialties")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakemberKereso.Models.Occupation", "Occupation")
                        .WithMany("ExpertSpecialties")
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Occupation");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Job", b =>
                {
                    b.HasOne("SzakemberKereso.Models.User", "InitiatingUser")
                        .WithMany("InitiatedJobs")
                        .HasForeignKey("InitiatingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakemberKereso.Models.ResidentialAddress", "Location")
                        .WithMany("Jobs")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakemberKereso.Models.Pricing", "Pricing")
                        .WithMany()
                        .HasForeignKey("PricingId");

                    b.HasOne("SzakemberKereso.Models.Service", "Service")
                        .WithMany("Jobs")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitiatingUser");

                    b.Navigation("Location");

                    b.Navigation("Pricing");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ResidentialAddress", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Settlement", "Settlement")
                        .WithMany("Addresses")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Service", b =>
                {
                    b.HasOne("SzakemberKereso.Models.ExpertSpecialty", "ExpertSpecialty")
                        .WithMany("Services")
                        .HasForeignKey("ExpertSpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakemberKereso.Models.Pricing", "Pricing")
                        .WithMany()
                        .HasForeignKey("PricingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpertSpecialty");

                    b.Navigation("Pricing");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Study", b =>
                {
                    b.HasOne("SzakemberKereso.Models.ExpertSpecialty", "ExpertSpecialty")
                        .WithMany("Studies")
                        .HasForeignKey("ExpertSpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpertSpecialty");
                });

            modelBuilder.Entity("SzakemberKereso.Models.TimeInterval", b =>
                {
                    b.HasOne("SzakemberKereso.Models.Job", "Job")
                        .WithMany("TimeIntervals")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Expert", b =>
                {
                    b.Navigation("ExpertSpecialties");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ExpertSpecialty", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("Studies");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Job", b =>
                {
                    b.Navigation("TimeIntervals");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Occupation", b =>
                {
                    b.Navigation("ExpertSpecialties");
                });

            modelBuilder.Entity("SzakemberKereso.Models.ResidentialAddress", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Service", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SzakemberKereso.Models.Settlement", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("SzakemberKereso.Models.User", b =>
                {
                    b.Navigation("Expert");

                    b.Navigation("InitiatedJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
